version: "3.9"

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    restart: always

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: chatbot
      POSTGRES_PASSWORD: chatbotpass
      POSTGRES_DB: chatbotdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  app:
    build: ./app
    command: gunicorn --worker-class eventlet -w 1 run:app --bind 0.0.0.0:5000
    environment:
      FLASK_ENV: production
      DATABASE_URL: postgres://chatbot:chatbotpass@postgres/chatbotdb
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - redis
      - postgres
    restart: always
    deploy:
      replicas: 3  # scale to 3 app instances
      restart_policy:
        condition: on-failure

volumes:
  postgres_data:
